version: "3.8"
services:
  db:
    image: postgres:16.1-bullseye
    env_file: 
      - .env
    volumes: 
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment: 
      - PGDATA=/var/lib/postgresql/data/pgdata   

  app:
    build: ./backend/
    depends_on:
      - db
    ports:
      - "80:80"

volumes:
  app-db-data:

